const routes = {
    signin: "signin",
    signinInternational: "login-international",
    signupInternational: "signup-international",
    getGeoLocation: "get-geolocation",
    getDistance:"get-distance",
    getPanchang:"get-panchang",
    getBanners:"get-banners",
    getTempleByCategory:"get-temple-by-category",
    getNewsEvents:"get-news-events",
    getTemplePujas:"get-temple-pujas",
    getStotras:"get-stotras",
    getCategories:"get-categories",
    getVideos:"get-videos",
    getStotraDetails:"get-stotra-details/",
    getTempleDetails:"get-temple-details/",
    getSearchResult:"get-search-result",
    countries: "country-list",
    list: "list",
    get: "get/",
    terms:"page/terms",
    privacy: "page/privacy-policy",
    mylist: "my-list",
    profile: "profile",
    setFavourite: "set-favourite",
    getFavourite: "get-favourite",
    getFavouriteList: "get-favourite-list",
    saveUserAddress: "save-user-address",
    getUserAddressList: "get-user-address-list",
    getUserTempleImageList: "get-user-temple-image-list",
    saveUserTempleImage: "save-user-temple-image",
    updateprofile: "profile/update",
    updateprofilepic: "profile/upload",
    contestlist: "contests/list",
    walletusage: "wallet-usage-limit",
    createContest: "contest-users/create",
    contesteventbycode: "contest-event-by-code",
    dailyreward: "daily-rewards",
    listdailyreward: "daily-rewards/list",
    collectdailyreward: "collect-daily-rewards",
    stateList: "state-list",
    signupCode: "apply-singup-code",
    avatarFree: "avatars/free-list",
    coinStoreList: "coin-stores/list",
    coinStoreGet: "coin-stores/get/",
    createRazTransaction: "account/create-raz-transaction",
    createCashfreeTransaction: "account/create-cashfree-transaction",
    avatarList: "avatar-categories/list",
    rewardCatList: "reward-categories/list",
    rewardProdMyList: "reward-products/my-list",  
    leaderboardsList: "event-leaderboards/list",  
    levelsList: "levels/list",  
    howToJoin: "how-to-play/list",
    myContestList: "contests/my-list",
    myEventsList: "events/my-list",
    gameStatistics: "account/game-statistics",
    leaderboard: "leaderboard-",
    applyReward: "apply-reward",
    buyAvatar: "buy-avatar",
    allPoints: "points/list",
    allPointsCategories: "point-categories/list",
    contestRate: "contest-rate",
    searchUserList: "users/list",  
    collegeList: "colleges/list",  

    applyEventCode: "contest-event-by-code",
    ticketList: "tickets/list",
    categoryList: "categories/search",
    searchGames: "games/search",
    uploadSS: "tickets/upload",
    createTicket: "tickets/create",
    getTicketChat: "tickets/get/",
    updateTicketChat: "tickets/update/", 
    rankSummeryByGame: "rank-summery-by-game",
    contestByGame: "contest-by-game",
    followings: "followings",
    followers: "followers",
    followUser: "follow-user",
    checkUser: "check",
    signup: "signup",
    createPaymentIntent: "create-payment-intent",
    createStripeTransactionWeb: "create-stripe-transaction-web",
    createStripePaymentIntentWeb: "create-payment-intent",
}
export default routes;
